# Generated by Django 4.1.1 on 2022-10-06 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('cod_depa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departament', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id_package', models.BigAutoField(max_length=255, primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('id_shipping', models.BigAutoField(max_length=255, primary_key=True, serialize=False)),
                ('price_shipping', models.DecimalField(decimal_places=3, max_digits=3)),
                ('date_shipping', models.DateField(default=datetime.date.today)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.address')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=3, max_digits=3)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('identify', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('id_shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.shippingorder')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.state', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='gestion.user'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.package'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='gestion.user'),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.type'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('pos_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.municipio'),
        ),
    ]
