# Generated by Django 4.1.1 on 2022-10-09 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('id_address', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'direccion',
                'verbose_name_plural': 'direcciones',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('cod_depa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departament', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('id_package', models.BigAutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Paquete',
            },
        ),
        migrations.CreateModel(
            name='ShippingOrder',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('id_shipping', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_shipping', models.IntegerField(default=0)),
                ('date_shipping', models.DateField(default=datetime.date.today)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.address')),
            ],
            options={
                'verbose_name': 'Detalle del envio',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('id_state', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado del envio',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('id_type', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de paquete',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('identify', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'verbose_name': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('id_shipping_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.shippingorder')),
                ('id_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.state')),
            ],
            options={
                'verbose_name': 'Trazabilidad',
                'verbose_name_plural': 'Trazabilidades',
            },
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='gestion.user'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.package'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='gestion.user'),
        ),
        migrations.AddField(
            model_name='package',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.type'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación')),
                ('pos_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.municipio'),
        ),
    ]
