# Generated by Django 4.1.1 on 2022-10-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id_package',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingorder',
            name='id_shipping',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='id_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.state'),
        ),
    ]
