# Generated by Django 4.1.1 on 2022-10-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_package_id_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingorder',
            name='price_shipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
