# Generated by Django 4.1.1 on 2022-10-09 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_shippingorder_price_shipping_alter_type_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AddField(
            model_name='address',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='address',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='address',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='state',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='state',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='state',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='type',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='type',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='type',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='type',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
