# Generated by Django 4.1.1 on 2022-10-09 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_address_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AlterModelOptions(
            name='shippingorder',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AlterModelOptions(
            name='trazabilidad',
            options={'verbose_name': 'modelo base'},
        ),
        migrations.AddField(
            model_name='package',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='package',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='package',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='package',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='shippingorder',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='created_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='deleted_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='modified_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
